### ISSUE TITLE
CT: registerPhetioOrderDependency is not a function

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#185]
This was broken by https://github.com/phetsims/axon/commit/7a42c26116918dcf00ed928c96c5d9eb6a9e7a4a, see https://github.com/phetsims/phet-io/issues/1668#issuecomment-632986924.  Affects both gas-properties and gases-intro.

```
gas-properties : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/gas-properties/build/phet/gas-properties_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1590203195335%22%2C%22timestamp%22%3A1590207028797%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Bt.registerPhetioOrderDependency is not a function
TypeError: Bt.registerPhetioOrderDependency is not a function
at new t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/gas-properties/build/phet/gas-properties_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1590203195335%22%2C%22timestamp%22%3A1590207028797%7D&fuzz&memoryLimit=1000:912:1184444)
at new i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/gas-properties/build/phet/gas-properties_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1590203195335%22%2C%22timestamp%22%3A1590207028797%7D&fuzz&memoryLimit=1000:912:1191990)
at i.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/gas-properties/build/phet/gas-properties_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1590203195335%22%2C%22timestamp%22%3A1590207028797%7D&fuzz&memoryLimit=1000:912:2728)
at new i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/gas-properties/build/phet/gas-properties_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1590203195335%22%2C%22timestamp%22%3A1590207028797%7D&fuzz&memoryLimit=1000:912:1376188)
at i.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/gas-properties/build/phet/gas-properties_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1590203195335%22%2C%22timestamp%22%3A1590207028797%7D&fuzz&memoryLimit=1000:912:1380820)
at initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/gas-properties/build/phet/gas-properties_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1590203195335%22%2C%22timestamp%22%3A1590207028797%7D&fuzz&memoryLimit=1000:912:775976)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/gas-properties/build/phet/gas-properties_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1590203195335%22%2C%22timestamp%22%3A1590207028797%7D&fuzz&memoryLimit=1000:912:981022)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/gas-properties/build/phet/gas-properties_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1590203195335%22%2C%22timestamp%22%3A1590207028797%7D&fuzz&memoryLimit=1000:912:981347
id: Bayes Chrome
Snapshot from 5/22/2020, 9:06:35 PM
```

**Comment by samreid** [comment]
Fixed in https://github.com/phetsims/phet-io/issues/1668#issuecomment-633087807 and verified in CT, closing.
